// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNThnSH4QB2oza6kaG4PLRb-1-1L5k_0',
    appId: '1:928119471821:web:bdf000e56fbc8f8086b384',
    messagingSenderId: '928119471821',
    projectId: 'vitti-14130',
    authDomain: 'vitti-14130.firebaseapp.com',
    databaseURL: 'https://vitti-14130-default-rtdb.firebaseio.com',
    storageBucket: 'vitti-14130.appspot.com',
    measurementId: 'G-G3SHFW90Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJw6UlAjCIU9qsvwVsALsTwALOaJkgh4',
    appId: '1:928119471821:android:ca48ee96f82b1fe986b384',
    messagingSenderId: '928119471821',
    projectId: 'vitti-14130',
    databaseURL: 'https://vitti-14130-default-rtdb.firebaseio.com',
    storageBucket: 'vitti-14130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTqfxoSn4jEvuJnPSySlTtVhJumAK7KUE',
    appId: '1:928119471821:ios:1fa6ee7f46a68e3386b384',
    messagingSenderId: '928119471821',
    projectId: 'vitti-14130',
    databaseURL: 'https://vitti-14130-default-rtdb.firebaseio.com',
    storageBucket: 'vitti-14130.appspot.com',
    androidClientId: '928119471821-3mnlglatf0q8ms8js6roeruijf4bd894.apps.googleusercontent.com',
    iosClientId: '928119471821-qqrf3gtlve94ftek1krbfdvnli8vlpcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.vittiHeritageApp',
  );
}

