// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BwnIIHYuLxzFX1MH2LTVpv_YjiJ39h4',
    appId: '1:690265754298:web:7b282493c8ae5a54325083',
    messagingSenderId: '690265754298',
    projectId: 'vitti-3be83',
    authDomain: 'vitti-3be83.firebaseapp.com',
    storageBucket: 'vitti-3be83.appspot.com',
    measurementId: 'G-8E539VJME8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqkBPGyP02-_Ye1v6zCjXymo3tqHpRxko',
    appId: '1:690265754298:android:dc66d08b13a4c485325083',
    messagingSenderId: '690265754298',
    projectId: 'vitti-3be83',
    storageBucket: 'vitti-3be83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWSOOT1Esjd-pS38O5iDjONwb-lusvIRI',
    appId: '1:690265754298:ios:79d981009197c487325083',
    messagingSenderId: '690265754298',
    projectId: 'vitti-3be83',
    storageBucket: 'vitti-3be83.appspot.com',
    iosClientId: '690265754298-2mjbvskg9umuaqea613ssqfdeltvrjs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vittiHeritageApp',
  );
}
